# Explorer
Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel:
  '{20D04FE0-3AEA-1069-A2D8-08002B30309D}': # Bring back My Computer
    data: 0

Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\ClassicStartMenu:
  '{20D04FE0-3AEA-1069-A2D8-08002B30309D}': # Bring back My Computer
    data: 0
